# a statement after a return is unreachable

fun main(a:Int)->Int
    return a
    val b = 1 # error as b is unreachable

@-------------------
testcase_outputs/pathContext4.fpl:5:9: Statement is unreachable
Failed with 1 errors